# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/
#
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

default_job = "run"
env.CARGO_TERM_COLOR = "always"

[jobs.run]
command = ["cargo", "run"]
need_stdout = true

[jobs.sqlx-prepare]
command = ["cargo", "sqlx", "prepare"]
need_stdout = true

