// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { WarmupData, WarmupResponses, WarmupErrors, AuthMeData, AuthMeResponses, AuthGetUserData, AuthGetUserResponses, AuthGetUserErrors, DevicesTriggerData, DevicesTriggerResponses, DevicesTriggerErrors, DevicesListData, DevicesListResponses, ActivityLeaderboardData, ActivityLeaderboardResponses, ActivityLeaderboardErrors, WolpStreamData, WolpStreamResponses, WolpStreamErrors, LafitnessGetCheckinsData, LafitnessGetCheckinsResponses, LafitnessGetCheckinsErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const warmup = <ThrowOnError extends boolean = false>(options?: Options<WarmupData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<WarmupResponses, WarmupErrors, ThrowOnError>({
        url: '/warmup',
        ...options
    });
};

export const authMe = <ThrowOnError extends boolean = false>(options?: Options<AuthMeData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AuthMeResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/me',
        ...options
    });
};

export const authGetUser = <ThrowOnError extends boolean = false>(options: Options<AuthGetUserData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<AuthGetUserResponses, AuthGetUserErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user/{id}',
        ...options
    });
};

export const devicesTrigger = <ThrowOnError extends boolean = false>(options: Options<DevicesTriggerData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<DevicesTriggerResponses, DevicesTriggerErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/trigger',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const devicesList = <ThrowOnError extends boolean = false>(options?: Options<DevicesListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<DevicesListResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/device',
        ...options
    });
};

export const activityLeaderboard = <ThrowOnError extends boolean = false>(options?: Options<ActivityLeaderboardData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ActivityLeaderboardResponses, ActivityLeaderboardErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/activity/leaderboard',
        ...options
    });
};

export const wolpStream = <ThrowOnError extends boolean = false>(options: Options<WolpStreamData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<WolpStreamResponses, WolpStreamErrors, ThrowOnError>({
        url: '/wolp/stream',
        ...options
    });
};

/**
 * Fetch LA Fitness check-in history
 *
 * This endpoint logs into the LA Fitness website, scrapes the check-in history, and returns a list of check-ins sorted most-recent-first.
 *
 * This is an unauthenticated endpoint - the LA Fitness credentials are provided in the request body.
 */
export const lafitnessGetCheckins = <ThrowOnError extends boolean = false>(options: Options<LafitnessGetCheckinsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LafitnessGetCheckinsResponses, LafitnessGetCheckinsErrors, ThrowOnError>({
        url: '/lafitness/get_checkins',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};