// This file is auto-generated by @hey-api/openapi-ts

export type Action = {
    Shock: {
        duration: ActionDuration;
        intensity: ActionIntensity;
    };
} | {
    Beep: {
        duration: ActionDuration;
        intensity: ActionIntensity;
    };
} | {
    Vibrate: {
        duration: ActionDuration;
        intensity: ActionIntensity;
    };
} | 'Stop';

/**
 * Wrapper type for shocker activation duration in milliseconds.
 *
 * Enforces OpenShock API constraint that duration must be at least 300ms.
 * Maximum value is implicitly capped at 65535ms (u16::MAX).
 *
 * Implements `Deref` to u16 for easy access to the underlying value.
 */
export type ActionDuration = number;

/**
 * Wrapper type for shocker intensity level.
 *
 * Enforces OpenShock API constraint that intensity must be between 0-100 inclusive.
 * A value of 0 represents no intensity, while 100 represents maximum intensity.
 *
 * Implements `Deref` to u8 for easy access to the underlying value.
 */
export type ActionIntensity = number;

/**
 * Represents a single check-in at an LA Fitness location.
 */
export type CheckIn = {
    /**
     * The check-in date/time in UTC
     */
    datetime: string;
    /**
     * The raw date/time string from the LA Fitness website (e.g., "10/16/2025 18:26 PM PST")
     */
    datetime_raw: string;
    /**
     * The name of the LA Fitness location
     */
    location: string;
};

/**
 * Represents a device with its associated shockers.
 *
 * This is the response format when listing devices with their shockers,
 * providing a complete view of the user's OpenShock setup.
 */
export type DeviceWithShockers = {
    /**
     * When this device was first registered with OpenShock
     */
    createdOn: string;
    /**
     * Unique identifier for this device
     */
    id: string;
    /**
     * Human-readable name assigned to this device
     */
    name: string;
    /**
     * All shockers connected to this device
     */
    shockers: Array<Shocker>;
};

/**
 * Request body for fetching LA Fitness check-ins
 */
export type GetCheckinsRequest = {
    /**
     * LA Fitness account password
     */
    password: string;
    /**
     * LA Fitness account username
     */
    username: string;
};

/**
 * Response containing check-in history
 */
export type GetCheckinsResponse = {
    /**
     * List of check-ins, sorted most-recent-first
     */
    checkins: Array<CheckIn>;
};

export type HealthcheckResponse = {
    db: HealthcheckStatus;
};

export type HealthcheckStatus = 'Healthy' | 'Unhealthy';

export type Invoker = {
    /**
     * Represents an invocation by request of a user.
     */
    User: {
        id: string;
    };
} | {
    /**
     * Represents a system-level invocation, such as a background job or an internal service call.
     * The string used should be uniquely grep-able in the codebase.
     */
    System: {
        tag: string;
    };
};

export type Leaderboard = {
    leaders: Array<UserActivityWithDetails>;
};

/**
 * Represents a shocker unit that can be controlled via OpenShock.
 *
 * A shocker is a physical device that can deliver various types of stimulation
 * (shock, vibration, sound) and is connected to an OpenShock device/hub.
 */
export type Shocker = {
    /**
     * When this shocker was first registered
     */
    createdOn: string;
    /**
     * Unique identifier for this shocker
     */
    id: string;
    /**
     * Whether this shocker is currently paused (cannot receive commands)
     */
    isPaused: boolean;
    /**
     * The model/type of this shocker device
     */
    model: string;
    /**
     * Human-readable name assigned to this shocker
     */
    name: string;
    /**
     * RF ID used for radio communication with the shocker
     */
    rfId: number;
};

export type TriggerRequest = {
    /**
     * The action to perform with its parameters
     */
    action: Action;
    /**
     * The UUIDs of the shocker devices to control
     */
    shockerIds: Array<string>;
};

export type TriggerResponse = {
    message: string;
    success: boolean;
};

export type User = {
    createdAt: string;
    id: string;
    name: string;
    photoUrl?: string | null;
    updatedAt: string;
};

/**
 * API response struct for leaderboard with full user details.
 */
export type UserActivityWithDetails = {
    counts: {
        [key: string]: number;
    };
    totalActions: number;
    user: User;
};

export type ActivityLeaderboardData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of users to return (max: 100)
         */
        topN?: number | null;
        /**
         * Time window in seconds to look back (max: 7 days)
         */
        reachbackSeconds?: number | null;
    };
    url: '/activity/leaderboard';
};

export type ActivityLeaderboardErrors = {
    /**
     * Invalid parameters
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ActivityLeaderboardResponses = {
    /**
     * Activity leaderboard
     */
    200: Leaderboard;
};

export type ActivityLeaderboardResponse = ActivityLeaderboardResponses[keyof ActivityLeaderboardResponses];

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthMeErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type AuthMeResponses = {
    /**
     * Current invoker
     */
    200: Invoker;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type HealthcheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthcheck';
};

export type HealthcheckErrors = {
    /**
     * System is unhealthy
     */
    503: HealthcheckResponse;
};

export type HealthcheckError = HealthcheckErrors[keyof HealthcheckErrors];

export type HealthcheckResponses = {
    /**
     * System is healthy
     */
    200: HealthcheckResponse;
};

export type HealthcheckResponse2 = HealthcheckResponses[keyof HealthcheckResponses];

export type GetCheckinsData = {
    body: GetCheckinsRequest;
    path?: never;
    query?: never;
    url: '/lafitness/get_checkins';
};

export type GetCheckinsErrors = {
    /**
     * Invalid LA Fitness credentials
     */
    401: unknown;
    /**
     * Failed to fetch check-ins
     */
    500: unknown;
};

export type GetCheckinsResponses = {
    /**
     * Check-in history
     */
    200: GetCheckinsResponse;
};

export type GetCheckinsResponse2 = GetCheckinsResponses[keyof GetCheckinsResponses];

export type AuthGetUserData = {
    body?: never;
    path: {
        /**
         * User UUID
         */
        id: string;
    };
    query?: never;
    url: '/user/{id}';
};

export type AuthGetUserErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * User not found
     */
    404: unknown;
};

export type AuthGetUserResponses = {
    /**
     * User found
     */
    200: User;
};

export type AuthGetUserResponse = AuthGetUserResponses[keyof AuthGetUserResponses];

export type WarmupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/warmup';
};

export type WarmupErrors = {
    /**
     * Failed to warm up database
     */
    500: unknown;
};

export type WarmupResponses = {
    /**
     * Database warmed up successfully
     */
    200: unknown;
};

export type WolpStreamData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Stream ID or URL to fetch
         */
        id: string;
    };
    url: '/wolp/stream';
};

export type WolpStreamErrors = {
    /**
     * Invalid stream ID format
     */
    400: unknown;
    /**
     * Stream not found
     */
    404: unknown;
};

export type ZapDeviceListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/zap/device';
};

export type ZapDeviceListErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ZapDeviceListResponses = {
    /**
     * List of devices with shockers
     */
    200: Array<DeviceWithShockers>;
};

export type ZapDeviceListResponse = ZapDeviceListResponses[keyof ZapDeviceListResponses];

export type ZapTriggerData = {
    body: TriggerRequest;
    path?: never;
    query?: never;
    url: '/zap/trigger';
};

export type ZapTriggerErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ZapTriggerResponses = {
    /**
     * Action triggered
     */
    200: TriggerResponse;
};

export type ZapTriggerResponse = ZapTriggerResponses[keyof ZapTriggerResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};