// This file is auto-generated by @hey-api/openapi-ts

export type Invoker = {
    User: {
        id: string;
    };
} | {
    System: {
        tag: string;
    };
};

export type User = {
    id: string;
    createdAt: string;
    updatedAt: string;
    name: string;
    photoUrl?: string | null;
};

export type TriggerResponse = {
    success: boolean;
    message: string;
};

export type TriggerRequest = {
    /**
     * The UUIDs of the shocker devices to control
     */
    shockerIds: Array<string>;
    /**
     * The action to perform with its parameters
     */
    action: Action;
};

export type Action = 'Stop' | {
    Shock: {
        intensity: Intensity;
        duration: Duration;
    };
} | {
    Beep: {
        intensity: Intensity;
        duration: Duration;
    };
} | {
    Vibrate: {
        intensity: Intensity;
        duration: Duration;
    };
};

/**
 * Wrapper type for shocker intensity level.
 *
 * Enforces OpenShock API constraint that intensity must be between 0-100 inclusive. A value of 0 represents no intensity, while 100 represents maximum intensity.
 *
 * Implements `Deref` to u8 for easy access to the underlying value, and `Display` for readable string representation.
 */
export type Intensity = number;

/**
 * Wrapper type for shocker activation duration in milliseconds.
 *
 * Enforces OpenShock API constraint that duration must be at least 300ms. Maximum value is implicitly capped at 65535ms (u16::MAX).
 *
 * Implements `Deref` to u16 for easy access to the underlying value, and `Display` for readable string representation.
 */
export type Duration = number;

/**
 * Represents a device with its associated shockers.
 *
 * This is the response format when listing devices with their shockers, providing a complete view of the user's OpenShock setup.
 */
export type DeviceWithShockers = {
    /**
     * Unique identifier for this device
     */
    id: string;
    /**
     * Human-readable name assigned to this device
     */
    name: string;
    /**
     * When this device was first registered with OpenShock
     */
    createdOn: string;
    /**
     * All shockers connected to this device
     */
    shockers: Array<Shocker>;
};

/**
 * Represents a shocker unit that can be controlled via OpenShock.
 *
 * A shocker is a physical device that can deliver various types of stimulation (shock, vibration, sound) and is connected to an OpenShock device/hub.
 */
export type Shocker = {
    /**
     * Unique identifier for this shocker
     */
    id: string;
    /**
     * RF ID used for radio communication with the shocker
     */
    rfId: number;
    /**
     * The model/type of this shocker device
     */
    model: string;
    /**
     * Human-readable name assigned to this shocker
     */
    name: string;
    /**
     * Whether this shocker is currently paused (cannot receive commands)
     */
    isPaused: boolean;
    /**
     * When this shocker was first registered
     */
    createdOn: string;
};

export type Leaderboard = {
    leaders: Array<UserActivityWithDetails>;
};

/**
 * API response struct for leaderboard with full user details.
 */
export type UserActivityWithDetails = {
    user: User;
    counts: {
        [key: string]: number;
    };
    totalActions: number;
};

/**
 * Response containing check-in history
 */
export type GetCheckinsResponse = {
    /**
     * List of check-ins, sorted most-recent-first
     */
    checkins: Array<CheckIn>;
};

/**
 * Represents a single check-in at an LA Fitness location.
 */
export type CheckIn = {
    /**
     * The check-in date/time in RFC 3339 UTC format
     */
    datetime: string;
    /**
     * The raw date/time string from the LA Fitness website (e.g., "10/16/2025 18:26 PM PST")
     */
    datetime_raw: string;
    /**
     * The name of the LA Fitness location
     */
    location: string;
};

/**
 * Request body for fetching LA Fitness check-ins
 */
export type GetCheckinsRequest = {
    /**
     * LA Fitness account username
     */
    username: string;
    /**
     * LA Fitness account password
     */
    password: string;
};

export type WarmupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/warmup';
};

export type WarmupErrors = {
    default: unknown;
};

export type WarmupResponses = {
    200: unknown;
};

export type AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthMeResponses = {
    200: Invoker;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthGetUserData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/user/{id}';
};

export type AuthGetUserErrors = {
    default: unknown;
};

export type AuthGetUserResponses = {
    200: User;
};

export type AuthGetUserResponse = AuthGetUserResponses[keyof AuthGetUserResponses];

export type DevicesTriggerData = {
    body: TriggerRequest;
    path?: never;
    query?: never;
    url: '/trigger';
};

export type DevicesTriggerErrors = {
    default: unknown;
};

export type DevicesTriggerResponses = {
    200: TriggerResponse;
};

export type DevicesTriggerResponse = DevicesTriggerResponses[keyof DevicesTriggerResponses];

export type DevicesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/device';
};

export type DevicesListResponses = {
    200: Array<DeviceWithShockers>;
};

export type DevicesListResponse = DevicesListResponses[keyof DevicesListResponses];

export type ActivityLeaderboardData = {
    body?: never;
    path?: never;
    query?: {
        top_n?: number | null;
        reachback_seconds?: number | null;
    };
    url: '/activity/leaderboard';
};

export type ActivityLeaderboardErrors = {
    default: unknown;
};

export type ActivityLeaderboardResponses = {
    200: Leaderboard;
};

export type ActivityLeaderboardResponse = ActivityLeaderboardResponses[keyof ActivityLeaderboardResponses];

export type WolpStreamData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/wolp/stream';
};

export type WolpStreamErrors = {
    500: unknown;
};

export type WolpStreamResponses = {
    default: unknown;
};

export type LafitnessGetCheckinsData = {
    body: GetCheckinsRequest;
    path?: never;
    query?: never;
    url: '/lafitness/get_checkins';
};

export type LafitnessGetCheckinsErrors = {
    default: unknown;
};

export type LafitnessGetCheckinsResponses = {
    200: GetCheckinsResponse;
};

export type LafitnessGetCheckinsResponse = LafitnessGetCheckinsResponses[keyof LafitnessGetCheckinsResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};