import { createContext, useContext, useMemo } from "react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { createClient, type Client } from "./api_client/client";
import * as rq from "@tanstack/react-query";
import { getAuth } from "./auth";
import type { Options } from "./api_client/sdk.gen";
import type { TDataShape } from "./api_client/client/types.gen";

// Create a React context, `<ApiProvider/>`, that provides the API client and QueryClient.
const ApiContext = createContext<{ apiClient: Client } | null>(null);

/** Provide both the API client and TanStack QueryClient to the child components. */
export function ApiProvider({ children }: { children: React.ReactNode }) {
  const { queryClient, apiClient } = useMemo(() => {
    // Create the autogenerated API client.
    const apiClient = createClient({
      baseUrl: "/api/v1/",
    });

    // Intercept requests to add the Authorization header.
    apiClient.interceptors.request.use(async (request) => {
      const auth = await getAuth();
      if (!auth) {
        throw new Error(
          "api client intercaptor: no auth state found to authorize request",
        );
      }
      request.headers.set("Authorization", `Bearer ${auth.token}`);
      return request;
    });

    // Create the TanStack QueryClient (responsible for storing cached results).
    const queryClient = new QueryClient({});

    return { queryClient, apiClient };
  }, []);

  return (
    <QueryClientProvider client={queryClient}>
      <ApiContext.Provider value={{ apiClient }}>
        {children}
      </ApiContext.Provider>
    </QueryClientProvider>
  );
}

/**
 * Wrap TanStack useQuery to automatically thread in the API client.
 *
 * Usage:
 * ```
 *  const {data} = useQuery(
 *    devicesList,
 *    {query: {status: "active"}}, // parameters to the API call
 *    {refetchInterval: 1000}, // react-query options
 *  );
 *
 * ```
 */
function useQuery<
  TData extends TDataShape = TDataShape,
  TQueryFnData = unknown,
  TError = rq.DefaultError,
  TQueryKey extends rq.QueryKey = rq.QueryKey,
>(
  queryDef: (
    options?: Options<TData>,
  ) => rq.UseQueryOptions<TQueryFnData, TError, TQueryFnData, TQueryKey>,
  params?: Omit<Options<TData>, "client">,
  options?: Omit<
    rq.UseQueryOptions<TQueryFnData, TError, TQueryFnData, TQueryKey>,
    "queryFn" | "queryKey"
  >,
): rq.UseQueryResult<TQueryFnData, TError> {
  const apiClient = useContext(ApiContext);
  if (!apiClient) {
    throw new Error("useQuery must be used within an ApiProvider");
  }

  // Merge the API client into the query definition parameters.
  const opts = queryDef({
    client: apiClient.apiClient,
    ...params,
  } as Options<TData>);

  // Merge the react-query options into the API def options.
  return rq.useQuery({ ...opts, ...options });
}

/**
 * Wrap TanStack useSuspenseQuery to automatically thread in the API client.
 *
 * Usage:
 * ```
 *  const {data} = useSuspenseQuery(
 *    devicesList,
 *    {query: {status: "active"}}, // parameters to the API call
 *    {refetchInterval: 1000}, // react-query options
 *  );
 *
 * ```
 */
function useSuspenseQuery<
  TData extends TDataShape = TDataShape,
  TQueryFnData = unknown,
  TError = rq.DefaultError,
  TQueryKey extends rq.QueryKey = rq.QueryKey,
>(
  queryDef: (
    options?: Options<TData>,
  ) => rq.UseQueryOptions<TQueryFnData, TError, TQueryFnData, TQueryKey>,
  params?: Omit<Options<TData>, "client">,
  options?: Omit<
    rq.UseSuspenseQueryOptions<TQueryFnData, TError, TQueryFnData, TQueryKey>,
    "queryFn" | "queryKey"
  >,
): rq.UseSuspenseQueryResult<TQueryFnData, TError> {
  const apiClient = useContext(ApiContext);
  if (!apiClient) {
    throw new Error("useSuspenseQuery must be used within an ApiProvider");
  }

  // Merge the API client into the query definition parameters.
  const opts = queryDef({
    client: apiClient.apiClient,
    ...params,
  } as Options<TData>);

  // Convert UseQueryOptions to UseSuspenseQueryOptions and merge with options.
  const { queryFn, queryKey, ...queryOptions } = opts;
  
  // Handle skipToken case - useSuspenseQuery doesn't support skipToken
  if (queryFn === rq.skipToken) {
    throw new Error("useSuspenseQuery does not support skipToken - use regular useQuery instead");
  }
  
  return rq.useSuspenseQuery({ 
    queryFn: queryFn!, 
    queryKey, 
    ...queryOptions, 
    ...options 
  });
}

/**
 * Wrap TanStack useMutation to automatically thread in the API client.
 *
 * Usage:
 * ```
 *  const mutation = useMutation(
 *    mutationDevicesTrigger,
 *    {
 *      onSuccess: () => console.log('success'),
 *      onError: (error) => console.error(error)
 *    }
 *  );
 *
 *  // Usage: mutation.mutate({ body: { ... } })
 * ```
 */
function useMutation<
  TData extends TDataShape = TDataShape,
  TMutationFnData = unknown,
  TError = rq.DefaultError,
  TVariables = Omit<Options<TData>, "client">,
  TContext = unknown,
>(
  mutationDef: (
    options?: Partial<Options<TData>>,
  ) => rq.UseMutationOptions<TMutationFnData, TError, Options<TData>, TContext>,
  options?: Omit<
    rq.UseMutationOptions<TMutationFnData, TError, TVariables, TContext>,
    "mutationFn"
  >,
): rq.UseMutationResult<TMutationFnData, TError, TVariables, TContext> {
  const apiClient = useContext(ApiContext);
  if (!apiClient) {
    throw new Error("useMutation must be used within an ApiProvider");
  }

  // Get the mutation definition with the API client
  const mutationOptions = mutationDef({
    client: apiClient.apiClient,
  } as Partial<Options<TData>>);

  // Create a wrapper mutation function that accepts user variables and passes them through
  const wrappedMutationFn = (variables: TVariables) => {
    return mutationOptions.mutationFn!({
      client: apiClient.apiClient,
      ...variables,
    } as Options<TData>);
  };

  return rq.useMutation({
    mutationFn: wrappedMutationFn,
    ...options,
  });
}

export const $api = { useQuery, useSuspenseQuery, useMutation };
