// This file is auto-generated by @hey-api/openapi-ts

import { type Options, warmup, authMe, devicesTrigger, devicesList, activityLeaderboard } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { WarmupData, AuthMeData, DevicesTriggerData, DevicesTriggerResponse, DevicesListData, ActivityLeaderboardData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const warmupQueryKey = (options?: Options<WarmupData>) => createQueryKey('warmup', options);

export const queryWarmup = (options?: Options<WarmupData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await warmup({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: warmupQueryKey(options)
    });
};

export const authMeQueryKey = (options?: Options<AuthMeData>) => createQueryKey('authMe', options);

export const queryAuthMe = (options?: Options<AuthMeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await authMe({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: authMeQueryKey(options)
    });
};

export const mutationDevicesTrigger = (options?: Partial<Options<DevicesTriggerData>>): UseMutationOptions<DevicesTriggerResponse, DefaultError, Options<DevicesTriggerData>> => {
    const mutationOptions: UseMutationOptions<DevicesTriggerResponse, DefaultError, Options<DevicesTriggerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await devicesTrigger({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const devicesListQueryKey = (options?: Options<DevicesListData>) => createQueryKey('devicesList', options);

export const queryDevicesList = (options?: Options<DevicesListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await devicesList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: devicesListQueryKey(options)
    });
};

export const activityLeaderboardQueryKey = (options?: Options<ActivityLeaderboardData>) => createQueryKey('activityLeaderboard', options);

export const queryActivityLeaderboard = (options?: Options<ActivityLeaderboardData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await activityLeaderboard({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: activityLeaderboardQueryKey(options)
    });
};