// This file is auto-generated by @hey-api/openapi-ts

import { type Options, activityLeaderboard, authMe, healthcheck, getCheckins, authGetUser, warmup, wolpStream, zapDeviceList, zapTrigger } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { ActivityLeaderboardData, AuthMeData, HealthcheckData, GetCheckinsData, GetCheckinsResponse2, AuthGetUserData, WarmupData, WolpStreamData, ZapDeviceListData, ZapTriggerData, ZapTriggerResponse } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const activityLeaderboardQueryKey = (options?: Options<ActivityLeaderboardData>) => createQueryKey('activityLeaderboard', options);

/**
 * Get the activity leaderboard for the most active users
 */
export const queryActivityLeaderboard = (options?: Options<ActivityLeaderboardData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await activityLeaderboard({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: activityLeaderboardQueryKey(options)
    });
};

export const authMeQueryKey = (options?: Options<AuthMeData>) => createQueryKey('authMe', options);

/**
 * Get the current authenticated user's invoker information
 */
export const queryAuthMe = (options?: Options<AuthMeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await authMe({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: authMeQueryKey(options)
    });
};

export const healthcheckQueryKey = (options?: Options<HealthcheckData>) => createQueryKey('healthcheck', options);

/**
 * Healthcheck endpoint
 */
export const queryHealthcheck = (options?: Options<HealthcheckData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await healthcheck({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: healthcheckQueryKey(options)
    });
};

/**
 * Fetch LA Fitness check-in history
 * This endpoint logs into the LA Fitness website, scrapes the check-in history,
 * and returns a list of check-ins sorted most-recent-first.
 *
 * This is an unauthenticated endpoint - the LA Fitness credentials are provided
 * in the request body.
 */
export const mutationGetCheckins = (options?: Partial<Options<GetCheckinsData>>): UseMutationOptions<GetCheckinsResponse2, DefaultError, Options<GetCheckinsData>> => {
    const mutationOptions: UseMutationOptions<GetCheckinsResponse2, DefaultError, Options<GetCheckinsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await getCheckins({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const authGetUserQueryKey = (options: Options<AuthGetUserData>) => createQueryKey('authGetUser', options);

/**
 * Get a user by their UUID
 */
export const queryAuthGetUser = (options: Options<AuthGetUserData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await authGetUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: authGetUserQueryKey(options)
    });
};

export const warmupQueryKey = (options?: Options<WarmupData>) => createQueryKey('warmup', options);

/**
 * Warmup route.
 * On Lambda, we need to warm up a couple things:
 * - The Aurora database, which will take ~10s to wake up from cold start.
 * - The Lambda, which is already warm by the time this code runs, but is still triggered
 * by the incoming HTTP request.
 *
 * The frontend will call this route when it loads, so that we start warming up all the stuff (hopefully) before the user tries to do anything.
 *
 * This is an unauthenticated route, because we want to be able to call it before the user
 * needs to use the API to sign in.
 */
export const queryWarmup = (options?: Options<WarmupData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await warmup({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: warmupQueryKey(options)
    });
};

export const wolpStreamQueryKey = (options: Options<WolpStreamData>) => createQueryKey('wolpStream', options);

/**
 * Redirect to a stream M3U8 URL from hdontap service
 */
export const queryWolpStream = (options: Options<WolpStreamData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await wolpStream({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: wolpStreamQueryKey(options)
    });
};

export const zapDeviceListQueryKey = (options?: Options<ZapDeviceListData>) => createQueryKey('zapDeviceList', options);

/**
 * List all OpenShock devices and shockers for the authenticated user
 */
export const queryZapDeviceList = (options?: Options<ZapDeviceListData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await zapDeviceList({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: zapDeviceListQueryKey(options)
    });
};

/**
 * Trigger an action on one or more OpenShock devices
 */
export const mutationZapTrigger = (options?: Partial<Options<ZapTriggerData>>): UseMutationOptions<ZapTriggerResponse, DefaultError, Options<ZapTriggerData>> => {
    const mutationOptions: UseMutationOptions<ZapTriggerResponse, DefaultError, Options<ZapTriggerData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await zapTrigger({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};