// This file is auto-generated by @hey-api/openapi-ts

import { type Options, warmup, authGetMe, triggerTriggerAction, deviceGetDevices } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { WarmupData, AuthGetMeData, TriggerTriggerActionData, TriggerTriggerActionResponse, DeviceGetDevicesData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const warmupQueryKey = (options?: Options<WarmupData>) => createQueryKey('warmup', options);

export const warmupOptions = (options?: Options<WarmupData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await warmup({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: warmupQueryKey(options)
    });
};

export const authGetMeQueryKey = (options?: Options<AuthGetMeData>) => createQueryKey('authGetMe', options);

export const authGetMeOptions = (options?: Options<AuthGetMeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await authGetMe({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: authGetMeQueryKey(options)
    });
};

export const triggerTriggerActionMutation = (options?: Partial<Options<TriggerTriggerActionData>>): UseMutationOptions<TriggerTriggerActionResponse, DefaultError, Options<TriggerTriggerActionData>> => {
    const mutationOptions: UseMutationOptions<TriggerTriggerActionResponse, DefaultError, Options<TriggerTriggerActionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await triggerTriggerAction({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deviceGetDevicesQueryKey = (options?: Options<DeviceGetDevicesData>) => createQueryKey('deviceGetDevices', options);

export const deviceGetDevicesOptions = (options?: Options<DeviceGetDevicesData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await deviceGetDevices({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: deviceGetDevicesQueryKey(options)
    });
};